### PR TITLE
opscode2chef

### PR DESCRIPTION
**Pull request by someara**

### CODE REVIEW

**Comment by svanzoest** [comment]
:+1: feel free to merge it or I will take care of it later today.

**Comment by someara** [comment]
Doesn't look like I have commit bits anymore. Brb, flying to LA =)
-s

On Wed, Feb 18, 2015 at 11:48 AM, Sander van Zoest <notifications@github.com

**Comment by svanzoest** [comment]
Ahh okay.
I will look into that too.
See you at scale?

-- Sander

**Comment by someara** [comment]
yep!

On Wed, Feb 18, 2015 at 11:51 AM, Sander van Zoest <notifications@github.com
> wrote:

> Ahh okay.
> I will look into that too.
> See you at scale?
>
> -- Sander
>

**Pull request merged**
